name: Sentiment Analysis App CI/CD

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint code
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t <YOUR_DOCKER_USERNAME>/sentiment-analysis-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: <YOUR_DOCKER_USERNAME>
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push <YOUR_DOCKER_USERNAME>/sentiment-analysis-app

  monitor:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      # Add steps for setting up monitoring tools like Prometheus and Grafana
      # ...

